jpprojeto/urls.py
# -*- coding: utf-8 -*-

"""{{ project_name }} URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/{{ docs_version }}/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.shortcuts import render
from django.conf.urls import url
from django.contrib import admin
from abastecimento.views import home,balancotable,labels_available,labels_favorites,update_labels_favorites,get_veiculo_km
from django.conf.urls import patterns
from django.contrib import admin
from django.http import HttpResponse
from abastecimento.models import Locacao,Veiculo,ManutencaoVeiculo
from django.forms import modelformset_factory
from django.forms import ModelForm
from django import forms
from django.shortcuts import redirect
import datetime
from django.template import Context, Template
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.contrib.auth.decorators import login_required

admin.autodiscover()
from django import template


class LocacaoForm(ModelForm):
    readonly = ('hodometroInicial',)
    hodometroInicial =  forms.CharField(widget=forms.TextInput(attrs={'readonly':'True'}))
    data_inicio =  forms.DateField(input_formats=['%d/%m/%Y'],widget=forms.DateInput(attrs={'readonly':'True'},format='%d/%m/%Y'))
    data_fim =  forms.DateField(input_formats=['%d/%m/%Y'],widget=forms.DateInput(attrs={'readonly':'True'},format='%d/%m/%Y'))
    class Media:
        js = ['/static/js/action_change.js']
    def __init__(self, *args, **kwargs):
        super(LocacaoForm, self).__init__(*args, **kwargs)
        if kwargs.get('instance',None) and kwargs.get('instance',None).pk:
            self.fields['veiculo'].disabled = True
            self.fields['obra'].disabled = True

    class Meta:
        model = Locacao
        exclude=('criado_date','atualizado_date','hodometro_date')
        readonly = ('hodometroInicial','data_inicio','data_fim')

@login_required
def locacao(request,id):
    # return HttpResponse("Hello!")
    locacao = Locacao()
    # author_form = AuthorModelForm(instance=locacao) # setup a form for the parent
    # LocacaoFormSet = modelformset_factory(Locacao, exclude=('criado_date','atualizado_date'))
    form = LocacaoForm(request.POST or None, instance=locacao)
    # formset = LocacaoFormSet()
    locacaos = Locacao.objects.all()

    return render(request, 'locacao/locacao.html',{u'title':'Locação','site_header':'Ancar Admin','formset': form,'locacaos':locacaos})

@login_required
def balanco(request,id):
    veiculos = Veiculo.objects.all()
    return render(request, 'custos/balanco.html',{u'title':'balanco','site_header':'Ancar Admin'})

@login_required
def abastecimento_grafico(request,id):
    # 
    # context = template.RequestContext(request)
    return render(request, 'abastecimento/graficos.html',{u'title':'balanco','site_header':'Ancar Admin'})

@login_required
def save_locacao(request,id):
    if id is not None:
        locacao = Locacao.objects.get(pk=id)  # if this is an edit form, replace the author instance with the existing one
    else:
        locacao = Locacao()

    if request.POST:
        form = LocacaoForm(request.POST or None, instance=locacao)

        if form.is_valid():
            locacao = form.save(commit=True)
            if locacao.data_fim>=locacao.veiculo.hodometro_date:
                hodometro_diff = locacao.hodometroFinal - locacao.veiculo.hodometro
                locacao.veiculo.hodometro = locacao.hodometroFinal
                locacao.veiculo.hodometro_date = locacao.data_fim
                locacao.veiculo.save()
                manutencaoProgramados = ManutencaoVeiculo.objects.filter(veiculo__placa=locacao.veiculo.placa)
                for item in manutencaoProgramados:
                    item.valorAcumulado = item.valorAcumulado + hodometro_diff
                    item.save()

    return redirect('/admin/locacao/')

@csrf_exempt
def delete_locacao(request,id):
    if id is not None:
        locacao = Locacao.objects.get(pk=id)  # if this is an edit form, replace the author instance with the existing one
        if locacao and request.method=='POST':
            locacao.delete()

    return redirect('/admin/locacao/')

def load_locacao(request,id):
    if id is not None:
        locacao = Locacao.objects.get(pk=id)  # if this is an edit form, replace the author instance with the existing one
    else:
        locacao = Locacao()
    form = LocacaoForm(request.POST or None, instance=locacao)
    form.readonly = form.readonly + ('veiculo',)
    return HttpResponse(form.as_p())

def get_admin_urls(urls):
    def get_urls():
        my_urls = [ 
            url(r'^abastecimento/balanco/(?:(?P<id>[0-9]+))?$', admin.site.admin_view(balanco)),
            url(r'^abastecimento/abastecimento_grafico/(?:(?P<id>[0-9]+))?$', admin.site.admin_view(abastecimento_grafico)),
            url(r'^locacao/(?:(?P<id>[0-9]+))?$', admin.site.admin_view(locacao)),
            url(r'^locacao/save_locacao/(?:(?P<id>[0-9]+))?$', admin.site.admin_view(save_locacao)),
            url(r'^locacao/delete_locacao/(?:(?P<id>[0-9]+))?$', admin.site.admin_view(delete_locacao)),
            url(r'^locacao/load_locacao/(?:(?P<id>[0-9]+))?$', admin.site.admin_view(load_locacao))
        ]
        return my_urls + urls
    return get_urls

admin_urls = get_admin_urls(admin.site.get_urls())
admin.site.get_urls = admin_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url(r'^calendar/', include('calendarium.urls')),
    url(r'^customgraph/', home),
    url(r'^balancotable/', balancotable),
    url(r'^get_veiculo_km/(?P<id>.+)', get_veiculo_km),
    url(r'^labels_available/', labels_available),
    url(r'^labels_favorites/', labels_favorites),
    url(r'^update_labels_favorites/', update_labels_favorites)
]

jpprojeto/templates/locacao/locacao.html
{% extends "admin/index.html" %}
{% load i18n admin_urls static admin_modify %}

{% load app_filters %}

{% block content  %}
	{% if request.user.is_superuser %}
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<script type="text/javascript" src="{% static "dygraphs/dygraph-combined.js" %} "></script>
	<link rel="stylesheet" type="text/css" href="{% static "chosen/chosen.css" %}" />
  		

	<link href='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.min.css' rel='stylesheet' />
	<link href='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.print.css' rel='stylesheet' media='print' />
	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script src='//cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.0/moment.min.js'></script>
	<script src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.min.js'></script>

	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.0/locale/pt-br.js"></script>
	  <script src="//fullcalendar.io/js/fullcalendar-3.0.1/locale-all.js"></script>

		{{formset.media}}
	<style>

		
		#calendar {
			max-width: 900px;
			margin: 0 auto;
		}

	</style>
	</head>
	<body>
		<select id="placas" class="chosen-select" data-placeholder="Escolha os Equipamentos ..." style="width:350px;padding:10px;" multiple="" tabindex="2">
      	</select>


		<div id='calendar'></div>

		<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel"> 
	        <span id="start" class="label label-info"></span>
	        <span  class=""> Até </span>
			<span id="end" class="label label-info"></span>
			</h4>
	      </div>
		<input type="hidden" id='locacal_id' name="locacal_id">

		<form method="POST" action="./save_locacao/">
		<button type="button" id="delteBtn" class="btn btn-danger">Deletar</button>
	      <div class="modal-body">
	            {% csrf_token %}
	            <div class="form-content">
	            	
				{{ formset.as_p }}
	            </div>

	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
	        <button type="submit" class="btn btn-primary">Salvar</button>
	      </div>
		</form>       
	    </div>
	  </div>
	  </div>
	  	<!-- Modal -->
	<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Deletar Locacao?
			</h4>
	      </div>
		<form method="POST" action="./delete_locacao/">
	      <div class="modal-body">
	            {% csrf_token %}
	      	
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
	        <button type="submit" class="btn btn-primary">Remover</button>
	      </div>
		</form>       
	    </div>
	  </div>
	  </div>
	</body>

	<script type="text/javascript" src="{% static "chosen/chosen.jquery.js" %} "></script>
	<script>

		$(document).ready(function() {
			$('#placas').on('change',function(evt, params) { 
				    var selected_values  = $("#placas.chosen-select").chosen().val();
		    		selected_values = selected_values?selected_values:[];
				    var string_selected_values =  selected_values.join(",");
			        $('#calendar').fullCalendar('rerenderEvents');

			  	});

			$.getJSON( "/labels_available", function( data ) {
	   			selectId = document.getElementById('placas');
	   			initial_index = selectId.options.length
				for(i = 0;i<data.length;i++) {   			
						selectId.options[initial_index] = new Option(data[i], data[i]);
						initial_index++;
 				}

				$("#placas.chosen-select").chosen({
					disable_search_threshold: 10,
					no_results_text: "Oops, Nada Encontrado!",
					width: "95%"
				});
				//$('#placas').on('change',change_mainGraph );
			});

			$('#delteBtn').bind('click',function(e){

	            $('#deleteModal form').attr('action','./delete_locacao/'+$('#locacal_id').val()+'')
	            $('#deleteModal .modal-body').html('<p> Teste locacao detalhes</p>')
				$('#deleteModal').modal('show');
			})

			$('#calendar').fullCalendar({
				locale: 'pt-br',

				header: {
					left: 'prev,next today',
					center: 'title',
					right: 'month,agendaWeek,agendaDay,listMonth'
				},
				// defaultDate: '2016-09-12',
				navLinks: true, // can click day/week names to navigate views
				selectable: true,
				selectHelper: true,
				eventClick: function(calEvent, jsEvent, view) {
					$.ajax({
				            "type"     : "GET",
				            "url"      : "./load_locacao/"+calEvent.id,
				            "dataType" : "html",
				            "cache"    : false,
				            "success"  : function(form) {
				                $('#myModal .modal-body .form-content').html(form);
				                $('#myModal form').attr('action','./save_locacao/'+calEvent.id+'')

								$('#myModal').modal('show');
								$("#myModal #start").html(calEvent.start.format("DD/MM/YYYY"))
								$('#delteBtn').show()
								$('#locacal_id').val(calEvent.id)
								if(calEvent.end)
									$("#myModal #end").html(calEvent.end.subtract(1,'days').format("DD/MM/YYYY"))
								else
									$("#myModal #end").html('')

				            }           
				    });
					
			        // change the border color just for fun
			        $(this).css('border-color', 'red');

			    },

				eventRender: function eventRender( event, element, view ) {
					if($('#placas').val()){
						return $('#placas').val().indexOf(event.veiculo)>=0
					}else{
						return true;
					}
			    },
				select: function(start, end) {
					// var title = prompt('Event Title:');
					$("#myModal #start").html(start.format("DD/MM/YYYY"))
					$("#myModal #end").html(end.subtract(1,'days').format("DD/MM/YYYY"))
					$('#myModal').modal('show');

	                $.ajax({
				            "type"     : "GET",
				            "url"      : "./load_locacao",
				            "dataType" : "html",
				            "cache"    : false,
				            "success"  : function(form) {
				                $('#myModal .modal-body .form-content').html(form);
				                $('#myModal form').attr('action','./save_locacao/')
			                	
								$('#id_data_inicio').parent().hide()
								$('#id_data_fim').parent().hide()

							    $('#id_data_inicio').val($("#myModal #start").text())
							    $('#id_data_fim').val($("#myModal #end").text())

								$('#delteBtn').hide()
								$('#myModal').modal('show');


				            }           
				    });

					$('#calendar').fullCalendar('unselect');

				},
				editable: false,
				eventLimit: true, // allow "more" link when too many events
				events: [

					{% for locacao in locacaos %}
					{
						id: '{{locacao.id}}',
						title: '{{locacao.title}}',
						start: "{{locacao.data_inicio|date:'Y-m-d'}}",
						end: "{{locacao.data_fim|addOneDay|date:'Y-m-d'}}",
						allDay:true,
						veiculo: '{{locacao.placa}}'

					},
					
					{%endfor%}
				],
			});
			
		});

	</script>


	{% endif %}
	{{ block.super }}

{% endblock %}